segma/urls.py
from django.contrib import admin
from django.urls import path,include
from segmapp import views
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index.as_view(),name='index'),
    path('login/',auth_view.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('app/',include('segmapp.urls')),
    path('bio/',views.make_bio.as_view(),name='bio'),
    path('updatebio/<pk>',views.update_bio.as_view(),name='bioupdate'),
    path('biodetail/<pk>',views.BioDetail.as_view(),name='biodetail'),
    path('requests/',views.RequestList.as_view(),name='requests'),
    path('followers/<pk>',views.Followerlist.as_view(),name='followers'),
    path('profile/<pk>',views.UserDetail.as_view(),name='profile'),
    path('search/',views.SearchResults.as_view(),name='search')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

segmapp/urls.py
from django.urls import path
from segmapp import views
app_name='app'
urlpatterns = [
path('create/',views.CreatePost.as_view(),name='create'),
path('postlist/<pk>',views.ListPosts.as_view(),name='posts'),
path('posts/edit/<pk>',views.EditPosts.as_view(),name='edit'),
path('posts/<pk>',views.DetailPosts.as_view(),name='detail'),
path('posts/comment/<slug>',views.comment,name='comment'),
path('posts/comment/delete/<pk>',views.DeleteComment.as_view(),name='delcom'),
path('<pk>',views.follow,name='follow'),
path('following/<pk>',views.Followinglist.as_view(),name='following'),
path('request/<pk>',views.RequestDetail.as_view(),name='request'),
path('accept/<pk>',views.accept,name='accept'),
path('reject/<pk>',views.reject,name='reject'),
path('posts/delete/<pk>',views.PostsDelete.as_view(),name='delete')
]

segmapp/models.py
from django.db import models
from django.contrib.auth.models import User
import os
class Post(models.Model):
    writer=models.ForeignKey(User,null=True,on_delete=models.CASCADE);
    title=models.CharField(max_length=2000,null=True);
    text=models.CharField(max_length=10000);
    time_created=models.DateTimeField(null=True);
    file = models.FileField(null=True,blank=True,upload_to='files')

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension
# Create your models here.

class Comment(models.Model):

    commenter=models.ForeignKey(User,null=True,on_delete=models.CASCADE);
    post=models.ForeignKey(Post,related_name='comments',null=True,on_delete=models.CASCADE);
    time_created=models.DateTimeField(null=True);
    text=models.CharField(max_length=10000);
    class Meta:
        ordering=['-time_created']
class Relation(models.Model):
    follower=models.ForeignKey(User,related_name='user',on_delete=models.CASCADE);
    following=models.ForeignKey(User,on_delete=models.CASCADE);
    class Meta:
        unique_together=[
        'follower','following'
        ]
class Request(models.Model):
    by=models.ForeignKey(User,related_name='req',on_delete=models.CASCADE);
    to=models.ForeignKey(User,on_delete=models.CASCADE);

class Bio(models.Model):
    user=models.OneToOneField(User,related_name='bio',on_delete=models.CASCADE,primary_key=True);
    profile_pic=models.ImageField(upload_to='profile_pics/',blank=True,null=True);
    text=models.CharField(max_length=10000)
    private=models.BooleanField(default=False)

segmapp/forms.py
from django import forms

from django.contrib.auth.models import User
from segmapp import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class UserCreateForm(UserCreationForm):
    class Meta:
        fields =('first_name','last_name','username','email','password1','password2')
        model = User
class PostEditForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields=('title','text','file')
        widgets={
        'text': forms.Textarea(attrs={"cols":50}),
        # 'image': PictureWidget
        }
        labels={
        'text':'',
        'image':''
        }
class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields=('text',)
        widgets={
        'text': forms.Textarea(attrs={"cols":50,"rows":5}),
        }
        labels={
        'text':''
        }
class BioForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['profile_pic'].required = True
    class Meta:
        model = models.Bio
        fields=('text','profile_pic')
        widgets={
        'text': forms.Textarea(attrs={"cols":50,"rows":5,"placeholder":'Enter your Bio information here.'}),
        }
        labels={
        'text':'',
        'profile_pic':'Upload Profile pic'
        }

segmapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy,reverse
from segmapp import forms
from django import forms as f
from django.http import HttpResponse, HttpResponseRedirect
from segmapp import models
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import TemplateView,CreateView,DeleteView,ListView,DetailView,UpdateView
from django.utils import timezone
from django.http import Http404
import time
class index(LoginRequiredMixin,ListView):
    login_url='login'
    model=models.Post
    template_name='index.html'
    context_object_name = 'posts'
    paginate_by = 3
    def get_context_data(self,**kwargs):
        context=super(index,self).get_context_data(**kwargs)
        context['b']=self.request.user.is_authenticated
        context['user']=self.request.user
        return context
    def get_queryset(self,*args,**kwargs):
        public=models.Bio.objects.filter(private=False)
        users=[self.request.user]
        for i in public:
            users.append(i.user)
        following=models.Relation.objects.filter(follower=self.request.user)
        for i in following:
            users.append(i.following)
        return models.Post.objects.filter(writer__in=users).order_by('-time_created')
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    template_name='signup.html'
    success_url=reverse_lazy('login')
class CreatePost(LoginRequiredMixin,CreateView):
    login_url='login'
    template_name='createpost.html'
    model=models.Post
    fields=('title','text','file')
    success_url=reverse_lazy('index')

    def get_context_data(self,**kwargs):
        context=super(CreatePost,self).get_context_data(**kwargs)
        context['user']=self.request.user
        return context
    def get_form(self, form_class=None):
        form = super(CreatePost, self).get_form(form_class)
        form.fields['text'].widget = f.Textarea(attrs={"placeholder" : "Enter your text here..","rows" : 8,"cols":50    },);
        form.fields['text'].label='';
        form.fields['title'].widget= f.TextInput(attrs={"placeholder" : "Enter Title Here.."})
        return form
    def form_valid(self,form):
        self.object=form.save(commit=False)
        self.object.writer_id=self.request.user.id;
        self.object.time_created=timezone.now();
        self.object.save()
        return super(CreatePost,self).form_valid(form)
class ListPosts(LoginRequiredMixin,ListView):
    login_url='login'
    model=models.Post
    context_object_name = 'posts'
    paginate_by = 3
    def get_context_data(self,**kwargs):
        context=super(ListPosts,self).get_context_data(**kwargs)
        context['u']=User.objects.get(id=self.kwargs['pk'])
        return context
    def get_queryset(self,*args,**kwargs):
        return models.Post.objects.all().filter(writer=models.User.objects.get(id=self.kwargs['pk'])).order_by('-time_created');
class EditPosts(LoginRequiredMixin,UpdateView):
    login_url='login'
    model=models.Post
    template_name='createpost.html'
    form_class=forms.PostEditForm
    success_url=reverse_lazy('index')
    def get_context_data(self,**kwargs):
        context=super(EditPosts,self).get_context_data(**kwargs)
        if context['object'].writer == self.request.user:
            return context
        else:
            raise Http404

class DetailPosts(LoginRequiredMixin,DetailView):
    login_url='login'
    model=models.Post
    def get_context_data(self,**kwargs):
        context=super(DetailPosts,self).get_context_data(**kwargs)
        f=models.Relation.objects.filter(follower=self.request.user,following=context['object'].writer).count()
        if context['object'].writer == self.request.user or f:
            return context
        else:
            raise Http404
class PostsDelete(LoginRequiredMixin,DeleteView):
    model=models.Post;
    login_url='login'
    success_url=reverse_lazy('index')
    def get_context_data(self,**kwargs):
        context=super(PostsDelete,self).get_context_data(**kwargs)
        print (context)
        if context['object'].writer == self.request.user:
            return context
        else:
            raise Http404
def comment(request,slug):
    if not request.user.is_authenticated:
        return reverse_lazy('login')
    post=get_object_or_404(models.Post,id=slug)
    if post.writer!=request.user :
        raise Http404;
    if request.method == "POST":
        c=forms.CommentForm(data=request.POST)

        if c.is_valid() :
            temp=c.save()
            temp.commenter=request.user
            temp.time_created=timezone.now()
            temp.post=post
            temp.save()
            c=forms.CommentForm()
            # return reverse_lazy('app:comment',kwargs={'slug':post.id})
    else:
        c=forms.CommentForm()
    return render(request,'segmapp/comment.html',context={'form':c,'user':request.user,'post':post,'object':post,'b':True,'l':True})
class DeleteComment(LoginRequiredMixin,DeleteView):
    model=models.Comment
    login_url='login'
    def get_success_url(self):
        obj=super(DeleteComment,self).get_object().post
        return reverse_lazy('app:comment',kwargs={'slug':obj.pk})
    def get_context_data(self,**kwargs):
        context=super(DeleteComment,self).get_context_data(**kwargs)
        if context['object'].post.writer == self.request.user or context['object'].commenter==self.request.user:
            return context
        else:
            raise Http404

class SearchResults(LoginRequiredMixin,ListView):
    model=User
    login_url='login'
    paginate_by =4
    template_name='search_results.html'
    def get_context_data(self,**kwargs):
        context=super(SearchResults,self).get_context_data(**kwargs)
        context['s']=self.request.GET.get('s');
        return context;
    def get_queryset(self):
        s=self.request.GET.get('s')
        return User.objects.filter(username__icontains=s)
class UserDetail(LoginRequiredMixin,DetailView):
    model=User
    login_url='login'
    template_name='user_detail.html'
    def get_context_data(self,**kwargs):
        context=super(UserDetail,self).get_context_data(**kwargs)
        b=models.Relation.objects.filter(follower=context['object']).count()
        a=models.Relation.objects.filter(following=context['object']).count()
        context['following']=b
        context['followers']=a
        return context
def follow(request,pk):
    following=User.objects.get(id=pk)
    follower=request.user
    t=models.Request(to=following,by=follower)
    t.save()
    return render(request,'index.html')
class RequestList(LoginRequiredMixin,ListView):
    model=models.Request
    paginate_by =4
    login_url='login'
    def get_queryset(self):
        user=self.request.user
        return models.Request.objects.filter(to__exact=user)
def accept(request,pk):
    r=models.Request.objects.get(id=pk)
    follower=r.by
    following=r.to
    t=models.Relation(follower=follower,following=following)
    t.save()
    r.delete()
    return render(request,'index.html')
class RequestDetail(LoginRequiredMixin,DetailView):
    model=models.Request
    login_url='login'
    template_name='segmapp/accept_request.html'
    def get_context_data(self,**kwargs):
        context=super(RequestDetail,self).get_context_data(**kwargs)
        b=models.Relation.objects.filter(follower=context['object'].by).count()
        a=models.Relation.objects.filter(following=context['object'].by).count()
        context['following']=b
        context['followers']=a
        context['u']=context['object'].by
        return context
class Followerlist(LoginRequiredMixin,ListView):
    model=models.Relation
    login_url='login'
    template_name='segmapp/followerlist.html'
    paginate_by =4
    def get_queryset(self):
        return models.Relation.objects.filter(following=self.kwargs['pk'])

class Followinglist(LoginRequiredMixin,ListView):
    model=models.Relation
    login_url='login'
    template_name='segmapp/followinglist.html'
    paginate_by =4
    def get_queryset(self):
        return models.Relation.objects.filter(follower=self.kwargs['pk'])

class make_bio(LoginRequiredMixin,CreateView):
    model=models.Bio
    login_url='login'
    template_name='segmapp/bio_create.html'
    success_url=reverse_lazy('index')
    form_class=forms.BioForm
    def form_valid(self,form):
        self.object=form.save(commit=False)
        self.object.user=self.request.user;
        self.object.save()
        return super(make_bio,self).form_valid(form)
class update_bio(LoginRequiredMixin,UpdateView):
    model=models.Bio
    login_url='login'
    template_name='segmapp/bio_create.html'
    success_url=reverse_lazy('index')
    form_class=forms.BioForm
    def form_valid(self,form):
        self.object=form.save(commit=False)
        self.object.user=self.request.user;
        self.object.save()
        return super(make_bio,self).form_valid(form)
class BioDetail(LoginRequiredMixin,DetailView):
    model=models.Bio
    login_url='login'
    template_name='user_detail.html'
    def get_context_data(self,**kwargs):
        context=super(BioDetail,self).get_context_data(**kwargs)
        context['followers']=models.Relation.objects.filter(following=context['object'].user).count()
        context['following']=models.Relation.objects.filter(follower=context['object'].user).count()
        context['f']=models.Relation.objects.filter(following=context['object'].user,follower=self.request.user).count()
        context['u']=context['object'].user
        context['user']=self.request.user
        return context
def reject(request,pk):
    r=models.Request.objects.get(id=pk)
    r.delete()
    return render(request,'index.html')

segmapp/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" >
    <link rel="stylesheet" href="{% static 'icon.css' %}">
        <title>Segma</title>
</head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
                <a class="navbar-brand font-weight-bold" href="{% url 'index' %}"><i class="fas fa-file"></i> Segma</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'index' %}"><i class="fas fa-home"></i> Home <span class="sr-only">(current)</span></a>
                    </li>



                  </ul>
                  <!------{{ request.get_host }}/blog/search/-->
                  <form class="form-inline my-2 my-lg-0" action='{% url "search"%}' method='GET'>
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" name="s">
                    <button type="submit" class=" text-white my-color btn-primary"><i class="fa fa-search"></i></button>
                </form>

                    {% if user.is_authenticated %}
                    <a href="{% url 'app:posts' pk=user.id %}" class="btn text-white m-2"><i class="fas fa-user-shield"></i> My Post</a>
                      <a href="{% url 'app:create'%}" class="btn text-white m-2"><i class="fas fa-user-edit"></i> New Post</a>
        <div class="dcontainer">


        <a class=" btn text-white m-2 dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-user"></i>   Social
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{% url 'requests'%}">Pending Requests</a>
          <a class="dropdown-item" href="{% url 'app:following' pk=user.id%}">Following</a>
          <a class="dropdown-item" href="{% url 'followers' pk=user.id%}">Followers</a>
        </div>
  </div>
                    {%if user.bio %}
                      <a href="{% url 'bioupdate' pk=user.id%} " class="btn text-white m-2"><i class="fas fa-user"></i> {{ user.username }}</a>
                    {% else %}
                    <a href="{% url 'bio' %} " class="btn text-white m-2"><i class="fas fa-user"></i> {{ user.username }}</a>
                    {% endif%}
                    <a href="{% url 'logout' %} " class="btn text-white m-2"><i class="fas fa-sign-out-alt"></i> Log Out</a>

                    {% else %}
                    <a href="{% url 'login' %} " class="btn text-white m-2"><i class="fas fa-user-tie"></i> Log In</a>

                    <a href="{% url 'signup' %} " class="btn text-white m-2"> <i class="fas fa-sign-in-alt"></i> Sign Up</a>
                    {% endif %}

                </div>
              </nav>
      <div class="container my-bg">
    {% block b1 %}

    {% endblock  %}
</div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="{% static 'main.js' %}"></script>
  </body>
</html>

segmapp/templates/createpost.html
{% extends 'base.html' %}
{% block b1 %}
{% load static%}
{% load crispy_forms_tags %}
{% if not form.instance.pk %}

<h1>Add Details For Your Post!!</h1>
{% else %}
<h1>Make Sure to Click on save!!</h1>
{% endif %}
<div class="content-section pt-2 mt-3 shadow-lg"  >
          <form action="" method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              <fieldset class="form-group">
                    <legend class="border-bottom mb-4">
                        Post
                    </legend>
                    {{ form|crispy }}
              </fieldset>
              <div class="form-group">

                  <button class="btn btn-outline-primary" type="submit"><i class="fas fa-upload"></i> Upload</button>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'app:posts' pk=user.id %}">Cancel</a>
              </div>
          </form>

      </div>
{% endblock %}

segmapp/templates/index.html
{% extends 'base.html' %}
{% block b1 %}
{%load static%}
<div class="row">
{% for object in posts%}
<div class="card" style="width: 31%;">
  {% if object.extension == '.jpg' or object.extension == 'jpeg' or object.extension == 'png' %}
    <a href="{{ object.file.url }}"  download ><img src="{{ object.file.url }}" alt="ss" class="card-img-top"/></a>
  {% elif object.extension == '.mp4' %}
    <div class="embed-responsive embed-responsive-16by9">
      <video id="video-1_html_api" class="vjs-tech" preload="auto" autoplay >
        <source src="{{ object.file.url }}" type="video/mp4" class="embed-responsive">
      </video>
    </div>
    <a href="{{ object.file.url }}"  download class="text-dark"><h5>{{ object.file }}</h5></a>
  {% endif%}
  <div class="card-body">
    <a href="{% url 'app:detail' pk=object.id%}">Detail</a>
  </div>
</div>
{%endfor%}
</div>
{% if is_paginated %}

  {% if page_obj.has_previous %}
    <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
  {% endif %}

  {% for num in page_obj.paginator.page_range %}
    {% if page_obj.number == num %}
      <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
      <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
    {% endif %}
  {% endfor %}

  {% if page_obj.has_next %}
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
    <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
  {% endif %}

{% endif %}


{% endblock %}

segmapp/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block b1 %}
<div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'signup' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock %}

segmapp/templates/search_results.html
{% extends 'base.html' %}
{% block b1 %}
{%load static%}
<h1 class="mb-3">Search Results for {{ s }}</h1>
    <ol class="mr-auto">
    {% for i in object_list %}
        <article class="media content-section">
          <li class="mr-auto"><a href="{%url 'biodetail' pk=i.id %} "class='article-title'>{{i.username}}</a></li>
        </article>
    {% endfor %}
    </ol>
{% endblock %}

segmapp/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block b1 %}
<div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Sign Up</button>
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
        </small>
    </div>
</div>
{% endblock %}

segmapp/templates/user_detail.html
{% extends 'base.html' %}
{% block b1 %}
{%load static%}
<div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ u.bio.profile_pic.url  }}">
        <div class="media-body">
          <h2 class="account-heading">{{ u.username }}</h2>
          <p class="text-secondary">{{ u.email }}</p>
        </div>
      </div>
      <div class="row">
<div class="col-sm-6" >
<h4><a href="{%url 'followers' pk=u.id%}" style="color:#fab107">Followers</a></h4><br>
<h5 class="text-left">{{followers}}</h5>
</div>
<div class="col-sm-6">
<h4><a href="{%url 'app:following' pk=u.id%} " style="color:#fab107">Following</a></h4><br>
<h5 class="text-left">{{following}}</h5>

</div>
</div>


{% if not f %}
<a href="{% url 'app:follow' pk=u.id%}" class="btn" id='login-submit'>Follow</a>
{% else %}
<h4><a href="{% url 'app:posts' pk=u.id%}" class="btn" id='login-submit'>Posts</a></h4>
{% endif %}
</div>
{% endblock %}