segma/urls.py
from django.contrib import admin
from django.urls import path,include
from segmapp import views
from django.contrib.auth import views as auth_view
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index.as_view(),name='index'),
    path('login/',auth_view.LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/',auth_view.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('app/',include('segmapp.urls')),
    path('bio/',views.make_bio.as_view(),name='bio'),
    path('updatebio/<pk>',views.update_bio.as_view(),name='bioupdate'),
    path('biodetail/<pk>',views.BioDetail.as_view(),name='biodetail'),
    path('requests/',views.RequestList.as_view(),name='requests'),
    path('followers/<pk>',views.Followerlist.as_view(),name='followers'),
    path('profile/<pk>',views.UserDetail.as_view(),name='profile'),
    path('search/',views.SearchResults.as_view(),name='search')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

segmapp/urls.py
from django.urls import path
from segmapp import views
app_name='app'
urlpatterns = [
path('create/',views.CreatePost.as_view(),name='create'),
path('postlist/<pk>',views.ListPosts.as_view(),name='posts'),
path('posts/edit/<pk>',views.EditPosts.as_view(),name='edit'),
path('posts/<pk>',views.DetailPosts.as_view(),name='detail'),
path('posts/comment/<slug>',views.comment,name='comment'),
path('posts/comment/delete/<pk>',views.DeleteComment.as_view(),name='delcom'),
path('<pk>',views.follow,name='follow'),
path('following/<pk>',views.Followinglist.as_view(),name='following'),
path('request/<pk>',views.RequestDetail.as_view(),name='request'),
path('accept/<pk>',views.accept,name='accept'),
path('reject/<pk>',views.reject,name='reject'),
path('posts/delete/<pk>',views.PostsDelete.as_view(),name='delete')
]

segmapp/models.py
from django.db import models
from django.contrib.auth.models import User
import os
class Post(models.Model):
    writer=models.ForeignKey(User,null=True,on_delete=models.CASCADE);
    title=models.CharField(max_length=2000,null=True);
    text=models.CharField(max_length=10000);
    time_created=models.DateTimeField(null=True);
    file = models.FileField(null=True,blank=True,upload_to='files')

    def extension(self):
        name, extension = os.path.splitext(self.file.name)
        return extension
# Create your models here.

class Comment(models.Model):

    commenter=models.ForeignKey(User,null=True,on_delete=models.CASCADE);
    post=models.ForeignKey(Post,related_name='comments',null=True,on_delete=models.CASCADE);
    time_created=models.DateTimeField(null=True);
    text=models.CharField(max_length=10000);
    class Meta:
        ordering=['-time_created']
class Relation(models.Model):
    follower=models.ForeignKey(User,related_name='user',on_delete=models.CASCADE);
    following=models.ForeignKey(User,on_delete=models.CASCADE);
    class Meta:
        unique_together=[
        'follower','following'
        ]
class Request(models.Model):
    by=models.ForeignKey(User,related_name='req',on_delete=models.CASCADE);
    to=models.ForeignKey(User,on_delete=models.CASCADE);

class Bio(models.Model):
    user=models.OneToOneField(User,related_name='bio',on_delete=models.CASCADE,primary_key=True);
    profile_pic=models.ImageField(upload_to='profile_pics/',blank=True,null=True);
    text=models.CharField(max_length=10000)
    private=models.BooleanField(default=False)

segmapp/forms.py
from django import forms

from django.contrib.auth.models import User
from segmapp import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class UserCreateForm(UserCreationForm):
    class Meta:
        fields =('first_name','last_name','username','email','password1','password2')
        model = User
class PostEditForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields=('title','text','file')
        widgets={
        'text': forms.Textarea(attrs={"cols":50}),
        # 'image': PictureWidget
        }
        labels={
        'text':'',
        'image':''
        }
class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields=('text',)
        widgets={
        'text': forms.Textarea(attrs={"cols":50,"rows":5}),
        }
        labels={
        'text':''
        }
class BioForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['profile_pic'].required = True
    class Meta:
        model = models.Bio
        fields=('text','profile_pic')
        widgets={
        'text': forms.Textarea(attrs={"cols":50,"rows":5,"placeholder":'Enter your Bio information here.'}),
        }
        labels={
        'text':'',
        'profile_pic':'Upload Profile pic'
        }

segmapp/views.py
from django.shortcuts import render
from django.urls import reverse_lazy,reverse
from segmapp import forms
from django import forms as f
from django.http import HttpResponse, HttpResponseRedirect
from segmapp import models
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import TemplateView,CreateView,DeleteView,ListView,DetailView,UpdateView
from django.utils import timezone
from django.http import Http404
import time
class index(LoginRequiredMixin,ListView):
    login_url='login'
    model=models.Post
    template_name='index.html'
    context_object_name = 'posts'
    paginate_by = 3
    def get_context_data(self,**kwargs):
        context=super(index,self).get_context_data(**kwargs)
        context['b']=self.request.user.is_authenticated
        context['user']=self.request.user
        return context
    def get_queryset(self,*args,**kwargs):
        public=models.Bio.objects.filter(private=False)
        users=[self.request.user]
        for i in public:
            users.append(i.user)
        following=models.Relation.objects.filter(follower=self.request.user)
        for i in following:
            users.append(i.following)
        return models.Post.objects.filter(writer__in=users).order_by('-time_created')
class SignUp(CreateView):
    form_class = forms.UserCreateForm
    template_name='signup.html'
    success_url=reverse_lazy('login')
class CreatePost(LoginRequiredMixin,CreateView):
    login_url='login'
    template_name='createpost.html'
    model=models.Post
    fields=('title','text','file')
    success_url=reverse_lazy('index')

    def get_context_data(self,**kwargs):
        context=super(CreatePost,self).get_context_data(**kwargs)
        context['user']=self.request.user
        return context
    def get_form(self, form_class=None):
        form = super(CreatePost, self).get_form(form_class)
        form.fields['text'].widget = f.Textarea(attrs={"placeholder" : "Enter your text here..","rows" : 8,"cols":50    },);
        form.fields['text'].label='';
        form.fields['title'].widget= f.TextInput(attrs={"placeholder" : "Enter Title Here.."})
        return form
    def form_valid(self,form):
        self.object=form.save(commit=False)
        self.object.writer_id=self.request.user.id;
        self.object.time_created=timezone.now();
        self.object.save()
        return super(CreatePost,self).form_valid(form)
class ListPosts(LoginRequiredMixin,ListView):
    login_url='login'
    model=models.Post
    context_object_name = 'posts'
    paginate_by = 3
    def get_context_data(self,**kwargs):
        context=super(ListPosts,self).get_context_data(**kwargs)
        context['u']=User.objects.get(id=self.kwargs['pk'])
        return context
    def get_queryset(self,*args,**kwargs):
        return models.Post.objects.all().filter(writer=models.User.objects.get(id=self.kwargs['pk'])).order_by('-time_created');
class EditPosts(LoginRequiredMixin,UpdateView):
    login_url='login'
    model=models.Post
    template_name='createpost.html'
    form_class=forms.PostEditForm
    success_url=reverse_lazy('index')
    def get_context_data(self,**kwargs):
        context=super(EditPosts,self).get_context_data(**kwargs)
        if context['object'].writer == self.request.user:
            return context
        else:
            raise Http404

class DetailPosts(LoginRequiredMixin,DetailView):
    login_url='login'
    model=models.Post
    def get_context_data(self,**kwargs):
        context=super(DetailPosts,self).get_context_data(**kwargs)
        f=models.Relation.objects.filter(follower=self.request.user,following=context['object'].writer).count()
        if context['object'].writer == self.request.user or f:
            return context
        else:
            raise Http404
class PostsDelete(LoginRequiredMixin,DeleteView):
    model=models.Post;
    login_url='login'
    success_url=reverse_lazy('index')
    def get_context_data(self,**kwargs):
        context=super(PostsDelete,self).get_context_data(**kwargs)
        print (context)
        if context['object'].writer == self.request.user:
            return context
        else:
            raise Http404
def comment(request,slug):
    if not request.user.is_authenticated:
        return reverse_lazy('login')
    post=get_object_or_404(models.Post,id=slug)
    if post.writer!=request.user :
        raise Http404;
    if request.method == "POST":
        c=forms.CommentForm(data=request.POST)

        if c.is_valid() :
            temp=c.save()
            temp.commenter=request.user
            temp.time_created=timezone.now()
            temp.post=post
            temp.save()
            c=forms.CommentForm()
            # return reverse_lazy('app:comment',kwargs={'slug':post.id})
    else:
        c=forms.CommentForm()
    return render(request,'segmapp/comment.html',context={'form':c,'user':request.user,'post':post,'object':post,'b':True,'l':True})
class DeleteComment(LoginRequiredMixin,DeleteView):
    model=models.Comment
    login_url='login'
    def get_success_url(self):
        obj=super(DeleteComment,self).get_object().post
        return reverse_lazy('app:comment',kwargs={'slug':obj.pk})
    def get_context_data(self,**kwargs):
        context=super(DeleteComment,self).get_context_data(**kwargs)
        if context['object'].post.writer == self.request.user or context['object'].commenter==self.request.user:
            return context
        else:
            raise Http404

class SearchResults(LoginRequiredMixin,ListView):
    model=User
    login_url='login'
    paginate_by =4
    template_name='search_results.html'
    def get_context_data(self,**kwargs):
        context=super(SearchResults,self).get_context_data(**kwargs)
        context['s']=self.request.GET.get('s');
        return context;
    def get_queryset(self):
        s=self.request.GET.get('s')
        return User.objects.filter(username__icontains=s)
class UserDetail(LoginRequiredMixin,DetailView):
    model=User
    login_url='login'
    template_name='user_detail.html'
    def get_context_data(self,**kwargs):
        context=super(UserDetail,self).get_context_data(**kwargs)
        b=models.Relation.objects.filter(follower=context['object']).count()
        a=models.Relation.objects.filter(following=context['object']).count()
        context['following']=b
        context['followers']=a
        return context
def follow(request,pk):
    following=User.objects.get(id=pk)
    follower=request.user
    t=models.Request(to=following,by=follower)
    t.save()
    return render(request,'index.html')
class RequestList(LoginRequiredMixin,ListView):
    model=models.Request
    paginate_by =4
    login_url='login'
    def get_queryset(self):
        user=self.request.user
        return models.Request.objects.filter(to__exact=user)
def accept(request,pk):
    r=models.Request.objects.get(id=pk)
    follower=r.by
    following=r.to
    t=models.Relation(follower=follower,following=following)
    t.save()
    r.delete()
    return render(request,'index.html')
class RequestDetail(LoginRequiredMixin,DetailView):
    model=models.Request
    login_url='login'
    template_name='segmapp/accept_request.html'
    def get_context_data(self,**kwargs):
        context=super(RequestDetail,self).get_context_data(**kwargs)
        b=models.Relation.objects.filter(follower=context['object'].by).count()
        a=models.Relation.objects.filter(following=context['object'].by).count()
        context['following']=b
        context['followers']=a
        context['u']=context['object'].by
        return context
class Followerlist(LoginRequiredMixin,ListView):
    model=models.Relation
    login_url='login'
    template_name='segmapp/followerlist.html'
    paginate_by =4
    def get_queryset(self):
        return models.Relation.objects.filter(following=self.kwargs['pk'])

class Followinglist(LoginRequiredMixin,ListView):
    model=models.Relation
    login_url='login'
    template_name='segmapp/followinglist.html'
    paginate_by =4
    def get_queryset(self):
        return models.Relation.objects.filter(follower=self.kwargs['pk'])

class make_bio(LoginRequiredMixin,CreateView):
    model=models.Bio
    login_url='login'
    template_name='segmapp/bio_create.html'
    success_url=reverse_lazy('index')
    form_class=forms.BioForm
    def form_valid(self,form):
        self.object=form.save(commit=False)
        self.object.user=self.request.user;
        self.object.save()
        return super(make_bio,self).form_valid(form)
class update_bio(LoginRequiredMixin,UpdateView):
    model=models.Bio
    login_url='login'
    template_name='segmapp/bio_create.html'
    success_url=reverse_lazy('index')
    form_class=forms.BioForm
    def form_valid(self,form):
        self.object=form.save(commit=False)
        self.object.user=self.request.user;
        self.object.save()
        return super(make_bio,self).form_valid(form)
class BioDetail(LoginRequiredMixin,DetailView):
    model=models.Bio
    login_url='login'
    template_name='user_detail.html'
    def get_context_data(self,**kwargs):
        context=super(BioDetail,self).get_context_data(**kwargs)
        context['followers']=models.Relation.objects.filter(following=context['object'].user).count()
        context['following']=models.Relation.objects.filter(follower=context['object'].user).count()
        context['f']=models.Relation.objects.filter(following=context['object'].user,follower=self.request.user).count()
        context['u']=context['object'].user
        context['user']=self.request.user
        return context
def reject(request,pk):
    r=models.Request.objects.get(id=pk)
    r.delete()
    return render(request,'index.html')

segmapp/templates/segmapp/accept_request.html
{% extends 'base.html' %}
{% block b1 %}
{%load static%}
<div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ u.bio.profile_pic.url  }}">
        <div class="media-body">
          <h2 class="account-heading">{{ u.username }}</h2>
          <p class="text-secondary">{{ u.email }}</p>
        </div>
      </div>
      <div class="row">
<div class="col-sm-6" >
<h4><a href="{%url 'followers' pk=u.id%}" style="color:#fab107">Followers</a></h4><br>
<h5 class="text-left">{{followers}}</h5>
</div>
<div class="col-sm-6">
<h4><a href="{%url 'app:following' pk=u.id%} " style="color:#fab107">Following</a></h4><br>
<h5 class="text-left">{{following}}</h5>

</div>
</div>
<a href="{% url 'app:accept' pk=object.id%}" class="btn" id='login-submit'>Accept</a>
<a href="{% url 'app:reject' pk=object.id%}" class="btn" id='login-submit'>Reject</a>
{% endblock %}

segmapp/templates/segmapp/bio_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block b1 %}
{%load static%}
<div class="content-section">
  <div class="media">
    <img class="rounded-circle account-img" src="{{ user.bio.profile_pic.url }}">
    <div class="media-body">
      <h2 class="account-heading">{{ user.username }}</h2>
      <p class="text-secondary">{{ user.email }}</p>
    </div>
  </div>
  <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4">Profile Info</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group">
          <button class="btn btn-outline-info" type="submit">Update</button>
      </div>
  </form>
</div>
{% endblock %}

segmapp/templates/segmapp/comment.html
{% extends 'segmapp/post_detail.html' %}
{% block b2 %}
{%load static%}
<h3>Hey {{user.username}} !! Add your Comment on {{post.title}}!!</h3>
<h4>Make Sure to Click on save to make your comment reach to {{post.writer}}</h4><br>
<form  method="post" class="login-form">
{%csrf_token%}
{{form.as_p}}

<input type="submit" class="btn btn-secondary btn-lg mt-1 mb-1" value="Save">
<a href="{% url 'app:posts' pk=user.id %}" class="btn btn-danger btn-lg mt-1 mb-1">Cancel</a>
</form>
{% endblock %}

segmapp/templates/segmapp/comment_confirm_delete.html
{% extends 'base.html' %}
{% block b1 %}
<form class="login-form" method="post">
{%csrf_token%}
{{form.as_p}}
<p><font size=32>Are You Sure You Want to Delete this Comment??</font></p>
<input type="submit" class="btn btn-danger" value="Confirm">
<a href="{%url 'app:comment' slug=object.post.id %}" class='btn btn-success'>Cancel</a>
</form>
{% endblock %}

segmapp/templates/segmapp/followerlist.html
{% extends 'base.html' %}
{% block b1 %}
{%load static%}

<h1 class="mb-3">Followers of {{ user.username }}</h1>
    <ol class="mr-auto">
    {% for i in object_list %}
        <article class="media content-section">
          <li class="mr-auto"><a href="{% url 'biodetail' pk=i.following.id %} "class='article-title'>{{i.follower.username}}</a></li>
        </article>
    {% endfor %}
    </ol>
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock %}

segmapp/templates/segmapp/followinglist.html
{% extends 'base.html' %}
{% block b1 %}
{%load static%}

<h1 class="mb-3">Following of {{ user.username }}</h1>
    <ol class="mr-auto">
    {% for i in object_list %}
        <article class="media content-section">
          <li class="mr-auto"><a href="{% url 'biodetail' pk=i.following.id %} "class='article-title'>{{i.following.username}}</a></li>
        </article>
    {% endfor %}
    </ol>
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock %}

segmapp/templates/segmapp/post_confirm_delete.html
{% extends 'base.html' %}
{% block b1 %}
<div class="content-section">
      <form method="POST">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Delete Post</legend>
              <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
              <a class="btn btn-outline-secondary" href="{%url 'app:detail' pk=object.id %}">Cancel</a>
          </div>
      </form>
  </div>
{% endblock %}

segmapp/templates/segmapp/post_detail.html
{% extends 'base.html' %}
{% block b1 %}
{%load static%}

<div class="jumbotron mt-3 shadow-lg">
<article class="media content-section shadow ">
   <a href="{{ object.writer.bio.profile_pic.url }} " target="_blank"> <img src="{{ object.writer.bio.profile_pic.url }}  " alt="" class="article-img rounded-circle img-thumbnail img-fluid">
   </a>
    <div class="media-body">
      <div class="">
        <div class="d-flex justify-content-between">
        <a class="mr-2 mt-0 mb-0  text-dark" href="{% url 'app:posts' pk=object.writer.id  %}"><h3>{{ object.writer }}</h3></a>
        <small class="text-muted  text-align-right">{{ object.time_created }}</small>
        </div>
        {% if object.writer != user %}
          <div class="form-group mt-0 pt-0 d-flex justify-content-end">
            <a href="{{ object.file.url }}" download class="btn btn-primary flex-last" type="submit"><i class="fas fa-download"></i> Downlaod</a>
          </div>
        {% endif %}
        <hr>
        {% if object.writer == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'app:edit' pk=object.id %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'app:delete' pk=object.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <div>
        {% if object.file %}
          {% if object.extension == '.jpg' or object.extension == 'jpeg' or object.extension == 'png' %}
            <a href="{{ object.file.url }}"  download ><img src="{{ object.file.url }}" alt="ss" class="img-fluid "></a>
            <a href="{{ object.file.url }}"  download class="text-dark"><h5>{{ object.file }}</h5></a>
          {% elif object.extension == '.mp4' %}
            <div class="embed-responsive embed-responsive-16by9">
              <video id="video-1_html_api" class="vjs-tech" preload="auto" autoplay >
                <source src="{{ object.file.url }}" type="video/mp4" class="embed-responsive">
              </video>
            </div>
            <a href="{{ object.file.url }}"  download class="text-dark"><h5>{{ object.file }}</h5></a>
          {% else %}
            <a href="{{ object.file.url }}"  download class="text-dark"><h5>{{ object.file }}</h5></a>
          {% endif %}
        {% endif %}
      </div>
      <h2>{{ object.title }}</h2>
      <p class="article-content">{{ object.text }}</p>
    </div>


  </article>
  <h1>Comments:</h1>
    {% for i in post.comments.all %}
  <div class="comment">

    <h2>{{i.text}}</h2>
    <h4>Commented by : {{i.commenter}}</h4>
    <h4>Date and Time : {{i.time_created}}</h4>
    <a href="{% url 'app:delcom' pk=i.id%}" class="btn btn-danger btn-lg mt-1 mb-1">Delete</a>
    <br>

  </div>
  {% empty %}
  <h4>No comments Yet!!</h4>
    {% endfor %}
    <br><br>

{% block b2%}

{% endblock %}
{% if not b%}
  <a href="comment/{{object.id}}"><img src="{% static 'comment.jpeg' %}" height=80 class='border'/></a>
{% endif %}
{% endblock %}

segmapp/templates/segmapp/post_list.html
{% extends 'base.html' %}
{% block b1 %}
{%load static%}

<h1 class="mb-3">Posts by {{ u.username }} ({{ page_obj.paginator.count }})</h1>
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.writer.bio.profile_pic.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'app:posts' pk=post.writer.id %}">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_created|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'app:detail' pk=post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.text }}</p>
          </div>
        </article>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock %}

segmapp/templates/segmapp/request_list.html
{% extends 'base.html' %}
{% block b1 %}
{%load static%}
<h1 class="mb-3">Follow Requests for {{ user.username }}</h1>
    <ol class="mr-auto">
    {% for i in object_list %}
        <article class="media content-section">
          <li class="mr-auto"><a href="{%url 'app:request' pk=i.id %} "class='article-title'>{{i.by.username}}</a></li>
        </article>
    {% endfor %}
    </ol>
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock %}